"""Format and post server-stored Snort replay results to COG Jira."""

import os
import re

from jira import JIRA
from jira.exceptions import JIRAError


JIRA_SERVER = "https://jira.talos.cisco.com"
PRIVATE = {"type": "role", "value": "Project Developer"}
COG_TICKET_PATTERN = re.compile(r"^COG-[1-9]\d{0,9}$")
TICKET_PATTERN = re.compile(r"^(?:COG|RESBZ)-[1-9]\d{0,9}$")
MAX_COMMENT_CHARS = min(
    max(int(os.getenv("JIRA_POST_MAX_COMMENT_CHARS", "30000")), 1000),
    32000,
)


class JiraPostError(RuntimeError):
    """Raised when replay results cannot be safely posted to Jira."""


def validate_cog_ticket(value):
    ticket = str(value or "").strip().upper()
    if not COG_TICKET_PATTERN.fullmatch(ticket):
        raise JiraPostError("Enter a COG ticket key such as COG-12345.")
    return ticket


def validate_ticket(value):
    ticket = str(value or "").strip().upper()
    if not TICKET_PATTERN.fullmatch(ticket):
        raise JiraPostError("Enter a COG or RESBZ ticket key such as COG-12345.")
    return ticket


def _line_value(value):
    return " ".join(str(value).replace("\r", " ").replace("\n", " ").split())


def _bounded_comment(comment):
    if len(comment) > MAX_COMMENT_CHARS:
        suffix = "\n\n_Result truncated by COG Wheelhouse to fit Jira's comment limit._"
        return comment[: MAX_COMMENT_CHARS - len(suffix)].rstrip() + suffix
    return comment


def format_replay_results(result):
    """Create bounded Jira wiki markup from one server-stored replay."""
    if not isinstance(result, dict):
        raise JiraPostError("No replay results are available to post.")
    lines = [
        "h2. Snort PCAP Replay Results",
        "Generated by Talos TE COG Wheelhouse.",
        "",
        f"*Snort version:* {_line_value(result.get('snort_version', 'Unknown'))}",
        f"*Policy:* {_line_value(result.get('policy', 'Unknown'))}",
        f"*Test SID:* {_line_value(result.get('sid', 'Unknown'))}",
        "",
        "h3. Capture summary",
    ]
    summary = result.get("capture_summary") or ["No capture summary was returned."]
    lines.extend(f"* {_line_value(item)}" for item in summary)
    lines.extend(["", "h3. PCAP analyzer summary"])
    analysis = result.get("content_analysis") or ["PCAP content analysis was not requested."]
    for item in analysis:
        value = _line_value(item)
        if value.startswith("=== ") and value.endswith(" ==="):
            lines.extend(["", f"h4. {value[4:-4]}"])
        elif value.startswith("[[PIGREPLAY_SECTION]] "):
            lines.extend(["", f"h4. {value.removeprefix('[[PIGREPLAY_SECTION]] ')}"])
        elif value.startswith("[[PIGREPLAY_TITLE]] "):
            lines.append(f"h5. {value.removeprefix('[[PIGREPLAY_TITLE]] ')}")
        else:
            lines.append(f"* {value}")
    lines.extend(["", "h3. Runtime and alerts", "{code}"])
    runtime = result.get("runtime_alerts") or ["No alerts or runtime output were returned."]
    lines.extend(str(item).replace("\r", "").replace("{code}", "\\{code\\}") for item in runtime)
    lines.append("{code}")
    return _bounded_comment("\n".join(lines))


def format_cr_results(batch):
    """Create bounded Jira wiki markup from server-recomputed CVE results."""
    if not isinstance(batch, list) or not batch:
        raise JiraPostError("No CVE CR results are available to post.")
    lines = ["h2. CVE CR Analysis Results", "Generated by Talos TE COG Wheelhouse."]
    for item in batch:
        cve = _line_value(item.get("cve", "Unknown CVE"))
        lines.extend(["", f"h3. {cve}"])
        if item.get("error"):
            lines.append(f"*Lookup error:* {_line_value(item['error'])}")
            continue
        research = item.get("research") or {}
        lines.extend([
            f"*Exploit evidence:* {_line_value(research.get('exploit_status', 'Unknown'))}",
            f"*Signature feasibility:* {_line_value(research.get('signature_feasibility', 'Unknown'))}",
        ])
        if research.get("signature_note"):
            lines.append(f"*Assessment note:* {_line_value(research['signature_note'])}")
        for link in research.get("exploit_links") or []:
            lines.append(f"* Exploit reference: {_line_value(link.get('url', ''))}")
        matches = item.get("snort_signatures") or []
        if matches:
            lines.append("*Downloaded Snort rule matches:* ")
            for match in matches:
                lines.extend([
                    f"** SID {_line_value(match.get('sid', 'Unknown'))} in {_line_value(match.get('source_name', 'rules'))}",
                    "{code}",
                    str(match.get("rule", "")).replace("\r", "").replace("{code}", "\\{code\\}"),
                    "{code}",
                ])
        else:
            lines.append("*Downloaded Snort rule matches:* None found")
    return _bounded_comment("\n".join(lines))


def _jira_client(username, password):
    if not username or not password:
        raise JiraPostError("Jira credentials are not available; sign in again.")
    try:
        return JIRA(
            basic_auth=(username, password),
            options={"server": JIRA_SERVER},
            get_server_info=False,
            max_retries=3,
            timeout=(5, 30),
        )
    except (JIRAError, OSError) as exc:
        raise JiraPostError("Unable to connect to Jira.") from exc


def post_replay_results(ticket, result, *, username=None, password=None, jira=None):
    """Add one private replay comment and return the canonical COG key."""
    issue_key = validate_cog_ticket(ticket)
    client = jira or _jira_client(username, password)
    try:
        issue = client.issue(issue_key)
        client.add_comment(
            issue,
            format_replay_results(result),
            visibility=PRIVATE,
        )
    except JIRAError as exc:
        status = getattr(exc, "status_code", None)
        if status == 404:
            raise JiraPostError(f"Jira ticket {issue_key} was not found.") from exc
        if status in {401, 403}:
            raise JiraPostError(f"Jira denied permission to comment on {issue_key}.") from exc
        raise JiraPostError(f"Jira could not update {issue_key}.") from exc
    return str(getattr(issue, "key", issue_key))


def post_cr_results(ticket, batch, *, username=None, password=None, jira=None):
    """Add one private CVE CR analysis comment and return its Jira key."""
    issue_key = validate_ticket(ticket)
    client = jira or _jira_client(username, password)
    try:
        issue = client.issue(issue_key)
        client.add_comment(issue, format_cr_results(batch), visibility=PRIVATE)
    except JIRAError as exc:
        status = getattr(exc, "status_code", None)
        if status == 404:
            raise JiraPostError(f"Jira ticket {issue_key} was not found.") from exc
        if status in {401, 403}:
            raise JiraPostError(f"Jira denied permission to comment on {issue_key}.") from exc
        raise JiraPostError(f"Jira could not update {issue_key}.") from exc
    return str(getattr(issue, "key", issue_key))
